### ISSUE TITLE
MaxHealth lower than HealthOnSpawn let me heal over the MaxHealth value

### ISSUE THREAD

**Issue by coco9515** [steven4547466/AdvancedSubclassing#12]
**Describe the bug**
I would expect that this code :
```yml
integer_options:
  # Max health of the class.
  MaxHealth: 1
  # The health the class spawns with.
  HealthOnSpawn: 500
```
Would have spawn me with 500HP (that works) but I could not heal since I would already be over my max HP - but I can actually heal myself.

**To Reproduce**
1. Create a class with "MaxHealth: 1" and "HealthOnSpawn: 500"
2. Spawn this class and hurt yourself
3. Try to heal yourself, you can heal.

**Expected behavior**
Any kind of heal would fail as I would already be above my "MaxHealth"

**Screenshots**
N/A

**Console Logs**
N/A

**Versioning**
 - AdvancedSubclassing Version 1.1.4:
 - Exiled Version 2.1.7.0:

**Additional context**
Another way to do it could be an ability that make the class unable to heal.

PS : Sorry, I realised I failed with the title of this post and I modified after
