### ISSUE TITLE
Incorrect Spawnpoints

### ISSUE THREAD

**Issue by coco9515** [steven4547466/AdvancedSubclassing#14]
**Describe the bug**
Some spawns are incorect (depends on map generations) like : 
- Gate A / B - as we can spawn inside the room = locked if we don't have the correct keycard
- Shelter - as we spawn inside = locked
- Glassbox (SCP 372's room) - can spawn inside the box, not always the best / logical
- 173 Armory - spawn on the stairs at the upper floor and fall down a bit (on the stairs and not to our doom); I altered with "SpawnOffsetZ : 5" and it seems to work all the time (because it only spawn there !)

**To Reproduce**
1. Create a class with any of those spawns points.
2. Spawn the class, and you MAY be at the incorect spot; you MAY need to regenerate the map to see it.

**Expected behavior**
For Shelter & Gate A / B : to spawn inside the site not locked on the elevator side.
For 173 Armory, to spawn inside the armory.
For Glassbox; mixed, I can see why spawn inside the glassbox as much as being inside the room or in front of the gate.

**Screenshots**
Gate B exemple : ![20201014140048_1](https://user-images.githubusercontent.com/42412909/95986291-075ccb00-0e26-11eb-9b59-16ace1858fed.jpg)

**Config File**
Only the class that spawns at 173 Armory : 
```yml
# Name of the Class
name: Ingenieur de confinement de 173

# Which roles can have this class
affects_roles:
- Scientist

string_options:
  # The message the user sees when they get the class.
  GotClassMessage: Tu es <color=yellow>l'ingénieur de confinement de 173</color>.
  # The message players see when they attempt to use an ability that's on cooldown.
  AbilityCooldownMessage: Ta capacité {ability} est en rechargement pour {seconds} secondes !
  # A badge for the player.
  Badge: L'ingénieur de confinement de 173
  # The color of the badge.
  BadgeColor: yellow
  # A message that will be announced by CASSIE when this subclass spawns.
  CassieMessage: 
  # The message people see when they run out of ability uses for any ability.
  OutOfAbilityUses: Tu n'as plus la capacité d'utiliser {ability} !

boolean_options:
  # Enables the class.
  Enabled: true
  # Disregards the value beneath it and uses the server default for friendly fire.
  DisregardHasFF: true
  # Enables friendly fire for this subclass, useful for traitorous subclasses, when a player with this option shoots a person on their team, everyone may shoot them regardless of DisregardTakesFF and TakesFriendlyFire.
  HasFriendlyFire: true
  # Disregards the value beneath it and uses the server default for friendly fire.
  DisregardTakesFF: true
  # Whether players on the same team of this subclass may shoot the player and may not be shot back.
  TakesFriendlyFire: true
  # If set to true, the subclass can only be given to a spawn wave. Defaults to false.
  OnlyAffectsSpawnWave: false
  # If set to true, the subclass can be given to both individuals and spawn waves. Defaults to false.
  AffectsSpawnWave : false
  # If set to false, the subclass will not be given to players after escaping. Defaults to true.
  GivenOnEscape : false

integer_options:
  # Max health of the class.
  MaxHealth: 100
  # The health the class spawns with.
  HealthOnSpawn: 100
  # Armor is a value that decreases over the course of the game, unless given the ability that stops it from doing so.
  # The max amount of armor the class has.
  MaxArmor: -1
  # The armor the class has on spawn.
  ArmorOnSpawn: -1
  # The max number of people that can have this class at any given moment - disregarding spawn waves.
  MaxAlive : 1
  # The max number of times this class can spawn per round. If this class is affecting a spawn wave, it is counted as 1. Defaults to an no max.
  MaxSpawnPerRound : 1
  # Any integer values from abilities go here as the <Ability>MaxUses

float_options:
  # The chance to get this class, not calculated with other classes for the same role.
  ChanceToGet: 10
  # The player's model scale across the selected axis.
  #ScaleX : 1
  #ScaleY : 1
  #ScaleZ : 1
  # The player's spawn offset relative to the selected axis.
  SpawnOffsetX : 0
  SpawnOffsetY : 0
  SpawnOffsetZ : 5
  # The damage multiplier this player has. A value of 2 will double their damage.
  OnHitDamageMultiplier : 1
  # Any float values from abilities go here
  
# You may have a list of RoomTypes where this class is teleported to at the start of the round. Use Unknown for the default spawn location.
spawn_locations:
- Lcz173Armory

# "None" instead of any object means nothing would be added, but it still clears the player's inventory.
# It may be empty, if that's the case the value is "spawn_items: {}" then it would spawn with the default items from the role.
spawn_items:
  0:
    KeycardContainmentEngineer: 100
  1:
    Flashlight: 33

# You can edit the default values of how must ammo a player has. Use -1 for default.
spawn_ammo:
  Nato556: -1
  Nato762: -1
  Nato9: -1

# Not all abilities are good, but they all add new things to the game.
# It may be empty, if that's the case, the value should be "abilities: []".
abilities: []

# You can set custom cooldowns for abilities that have cooldowns.
# This list should contain all abilites that could have cooldowns that the class has, even if you set them to 0.
# It may be empty, if that's the case, the value should be "ability_cooldowns: {}".
ability_cooldowns: {}

# With this list, you can give a subclass a list of other subclasses they can friendly fire upon.
# This value is a list of strings (which are other subclass names). It may be empty, if that's the case, the value should be "advanced_ff_rules: []".
advanced_ff_rules: []

# This is a list of roles that are unable to damage the subclass regardless of team.
# If you want it to be empty, you can use "roles_that_cant_damage: []".
roles_that_cant_damage: []

# This is the Team that players with this class can end the game with. "RIP" means the default team.
ends_round_with: RIP

# This adds the ability to give players with certain subclasses the ability to inflict any effects upon damage a player.
# If there is anything in the list, you have to add those to the float_options : "OnHit<EFFECT_NAME>Chance" which is the chance for the effect to be applied.
# And there's "OnHit<EFFECT_NAME>Duration" this is optional and is the duration of the effect.
on_hit_effects: []

# This adds the ability to give players with certain subclasses any effects on spawn.
# If there is anything in the list, you have to add those to the float_options : "OnSpawn<EFFECT_NAME>Chance" which is the chance for the effect to be applied.
# And there's "OnSpawn<EFFECT_NAME>Duration" this is optional and is the duration of the effect.
on_spawn_effects: []

# This adds the ability to give players with certain subclasses any effects when they are damaged based on the damage type.
# If there is anything in the list, you have to add those to the float_options : "OnDamaged<EFFECT_NAME>Chance" which is the chance for the effect to be applied.
# And there's "OnDamaged<EFFECT_NAME>Duration" this is optional and is the duration of the effect.
#on_damaged_effects:

# It defines what role the class will spawn as. "None" is the default meaning they spawn as the role they were going to.
spawns_as: None

# These define what role the class becomes upon escaping. There are options for cuffed and not cuffed.
# If this is set to "None", or is not provided, it will use the default. This does not work on classes that cannot escape.
escapes_as:
  cuffed: ChaosInsurgency
  not_cuffed: NtfScientist
```

**Console Logs**
N/A

**Versioning**
 - AdvancedSubclassing Version 1.1.5 :
 - Exiled Version 2.1.7.0 :

**Additional context**
I can see why you would want to spawn inside the Gate A / B; likewise for the Glassbox.
Why not create a spawnpoint inside and one outside each ?
