### ISSUE TITLE
FF failed

### ISSUE THREAD

**Issue by coco9515** [steven4547466/AdvancedSubclassing#23]
**Describe the bug**
We can't have FF between exact ssame role, not subclasses, just roles. Also not teams, but roles.

**To Reproduce**
1. Create any class with FF on
2. Get 2 player on the same role and can't kill either.

**Expected behavior**
FF works has intended.

**Screenshots**
N/A

**Config File**
```yml
# Name of the Class
name: Chaos Générique

# Which roles can have this class
affects_roles:
- ChaosInsurgency

string_options:
  # The message the user sees when they get the class.
  GotClassMessage: 
  # The message players see when they attempt to use an ability that's on cooldown.
  AbilityCooldownMessage: Ta capacité {ability} est en rechargement pour {seconds} secondes !
  # A badge for the player.
  Badge: 
  # The color of the badge.
  BadgeColor: 
  # A message that will be announced by CASSIE when this subclass spawns.
  CassieMessage: 
  # The message people see when they run out of ability uses for any ability.
  OutOfAbilityUses: Tu n'as plus la capacité d'utiliser {ability} !

boolean_options:
  # Enables the class.
  Enabled: true
  # Disregards the value beneath it and uses the server default for friendly fire.
  DisregardHasFF: true
  # Enables friendly fire for this subclass, useful for traitorous subclasses, when a player with this option shoots a person on their team, everyone may shoot them regardless of DisregardTakesFF and TakesFriendlyFire.
  HasFriendlyFire: true
  # Disregards the value beneath it and uses the server default for friendly fire.
  DisregardTakesFF: true
  # Whether players on the same team of this subclass may shoot the player and may not be shot back.
  TakesFriendlyFire: true
  # If set to true, the subclass can only be given to a spawn wave. Defaults to false.
  OnlyAffectsSpawnWave: false
  # If set to true, the subclass can be given to both individuals and spawn waves. Defaults to false.
  AffectsSpawnWave : true
  # If set to false, the subclass will not be given to players after escaping. Defaults to true.
  GivenOnEscape : true

integer_options:
  # Max health of the class.
  MaxHealth: 120
  # The health the class spawns with.
  HealthOnSpawn: 120
  # Armor is a value that decreases over the course of the game, unless given the ability that stops it from doing so.
  # The max amount of armor the class has.
  MaxArmor: 0
  # The armor the class has on spawn.
  ArmorOnSpawn: 0
  # The max number of people that can have this class at any given moment - disregarding spawn waves.
  MaxAlive : 1000
  # The max number of times this class can spawn per round. If this class is affecting a spawn wave, it is counted as 1. Defaults to an no max.
  MaxSpawnPerRound : 1000
  # Any integer values from abilities go here as the <Ability>MaxUses

float_options:
  # The chance to get this class, not calculated with other classes for the same role.
  ChanceToGet: 100
  # The player's model scale across the selected axis.
  #ScaleX : 1.15
  #ScaleY : 1.15
  #ScaleZ : 1.15
  # The player's spawn offset relative to the selected axis.
  SpawnOffsetX : 0
  SpawnOffsetY : 0
  SpawnOffsetZ : 0
  # The damage multiplier this player has. A value of 2 will double their damage.
  OnHitDamageMultiplier : 1
  
# You may have a list of RoomTypes where this class is teleported to at the start of the round. Use Unknown for the default spawn location.
spawn_locations:
- Unknown

# "None" instead of any object means nothing would be added, but it still clears the player's inventory.
# It may be empty, if that's the case the value is "spawn_items: {}" then it would spawn with the default items from the role.
spawn_items:
  0:
    KeycardChaosInsurgency: 100
  1:
    GunLogicer: 100
  2:
    Disarmer: 100
  3:
    Medkit: 100
  4:
    Painkillers: 100
  5:
    GunUSP: 50
  6:
    GrenadeFrag: 50

# You can edit the default values of how must ammo a player has. Use -1 for default.
spawn_ammo:
  Nato556: -1
  Nato762: -1
  Nato9: -1

# Not all abilities are good, but they all add new things to the game.
# It may be empty, if that's the case, the value should be "abilities: []".
abilities: []

# You can set custom cooldowns for abilities that have cooldowns.
# This list should contain all abilites that could have cooldowns that the class has, even if you set them to 0.
# It may be empty, if that's the case, the value should be "ability_cooldowns: {}".
ability_cooldowns: {}

# With this list, you can give a subclass a list of other subclasses they can friendly fire upon.
# This value is a list of strings (which are other subclass names). It may be empty, if that's the case, the value should be "advanced_ff_rules: []".
advanced_ff_rules: []

# This is a list of roles that are unable to damage the subclass regardless of team.
# If you want it to be empty, you can use "roles_that_cant_damage: []".
roles_that_cant_damage: []

# This is the Team that players with this class can end the game with. "RIP" means the default team.
ends_round_with: RIP

# This adds the ability to give players with certain subclasses the ability to inflict any effects upon damage a player.
# If there is anything in the list, you have to add those to the float_options : "OnHit<EFFECT_NAME>Chance" which is the chance for the effect to be applied.
# And there's "OnHit<EFFECT_NAME>Duration" this is optional and is the duration of the effect.
on_hit_effects: []

# This adds the ability to give players with certain subclasses any effects on spawn.
# If there is anything in the list, you have to add those to the float_options : "OnSpawn<EFFECT_NAME>Chance" which is the chance for the effect to be applied.
# And there's "OnSpawn<EFFECT_NAME>Duration" this is optional and is the duration of the effect.
on_spawn_effects: []

# This adds the ability to give players with certain subclasses any effects when they are damaged based on the damage type.
# If there is anything in the list, you have to add those to the float_options : "OnDamaged<EFFECT_NAME>Chance" which is the chance for the effect to be applied.
# And there's "OnDamaged<EFFECT_NAME>Duration" this is optional and is the duration of the effect.
#on_damaged_effects:

# It defines what role the class will spawn as. "None" is the default meaning they spawn as the role they were going to.
spawns_as: None

# These define what role the class becomes upon escaping. There are options for cuffed and not cuffed.
# If this is set to "None", or is not provided, it will use the default. This does not work on classes that cannot escape.
escapes_as:
  cuffed: NtfCadet
  not_cuffed: None
```

**Console Logs**
```
> [18:17:28] [DEBUG] [Subclass-1.2.0-pre004] Checking zombies
> [18:17:28] [DEBUG] [Subclass-1.2.0-pre004] Checking FF rules for Attacker: Wiirlak Target: Pyrrokx
> [18:17:28] [DEBUG] [Subclass-1.2.0-pre004] Checking zombies
> [18:17:28] [DEBUG] [Subclass-1.2.0-pre004] Checking classes
> [18:17:28] [DEBUG] [Subclass-1.2.0-pre004] Checking allowed damage rules for Attacker: Wiirlak to target role: NtfCadet
> [18:17:28] [DEBUG] [Subclass-1.2.0-pre004] Attacker: Wiirlak has not been granted friendly fire
> [18:17:28] [DEBUG] [Subclass-1.2.0-pre004] Checking takes friendly fire
> [18:17:28] [DEBUG] [Subclass-1.2.0-pre004] Not allowed to damage
> [18:17:28] [DEBUG] [Subclass-1.2.0-pre004] Checking FF rules in classes
```

**Versioning**
 - AdvancedSubclassing Version Subclass-1.2.0-pre004:
 - Exiled Version 2.1.9:

**Additional context**
Server have FF on, obviously.

**Comment by steven4547466** [comment]
Set DisregardHasFF and DisregardTakesFF to false. If this is true, it uses server default, let me know if it works!

**Comment by coco9515** [comment]
Still can't hurt people on the same role as me with this :
```yml
  # Disregards the value beneath it and uses the server default for friendly fire.
  DisregardHasFF: false
  # Enables friendly fire for this subclass, useful for traitorous subclasses, when a player with this option shoots a person on their team, everyone may shoot them regardless of DisregardTakesFF and TakesFriendlyFire.
  HasFriendlyFire: true
  # Disregards the value beneath it and uses the server default for friendly fire.
  DisregardTakesFF: true
  # Whether players on the same team of this subclass may shoot the player and may not be shot back.
  TakesFriendlyFire: true
```

I also tried : 
```yml
  # Disregards the value beneath it and uses the server default for friendly fire.
  DisregardHasFF: false
  # Enables friendly fire for this subclass, useful for traitorous subclasses, when a player with this option shoots a person on their team, everyone may shoot them regardless of DisregardTakesFF and TakesFriendlyFire.
  HasFriendlyFire: true
  # Disregards the value beneath it and uses the server default for friendly fire.
  DisregardTakesFF: false
  # Whether players on the same team of this subclass may shoot the player and may not be shot back.
  TakesFriendlyFire: true
```

**Comment by steven4547466** [comment]
Tested with this class:
```yml
name: Test2

affects_roles:
- ClassD

string_options:
  GotClassMessage: You are an <color=red>ExampleClass</color>, this is an example test.
  AbilityCooldownMessage: Your {ability} ability is on cooldown for {seconds} seconds!
  OutOfAbilityUses: Your {ability} is out of uses!
  HelpMessage: Example help message.
  Nickname: Test {name}

boolean_options:
  Enabled: true
  DisregardHasFF: false
  HasFriendlyFire: true
  DisregardTakesFF: false
  TakesFriendlyFire: true

integer_options:
  MaxHealth: 100
  HealthOnSpawn: 100
  MaxArmor: -1
  ArmorOnSpawn: -1
  HealGrenadeFlashMaxUses: 2
  HealGrenadeFragMaxUses: 2

float_options:
  ChanceToGet: 0

spawn_locations:
- Unknown

spawn_items:
  0:
    GunCOM15: 100

spawn_ammo:
  Nato556: -1
  Nato762: -1
  Nato9: -1

abilities: []

ability_cooldowns: {}

advanced_ff_rules: []

on_hit_effects: []

on_spawn_effects: []
```
had [this](https://www.youtube.com/watch?v=7k-wq3W8aG8) effect (sorry about the lag, the server I tested on is far from me). I still cannot reproduce the described effect.
