### ISSUE TITLE
(Optional Config) spawn_as

### ISSUE THREAD

**Issue by tpd1864blake** [steven4547466/AdvancedSubclassing#3]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
An optional value (either a String or a new Dictionary list) of role(s) that you get forceclassed as when being chosen for the subclass. For example, if you wanted to make a Custom SCP class that starts from the beginning of the round, you could make something like
```yml
name: SCP-966

affects_roles:
- ClassD
- Scientist
- FacilityGuard

string_options:
  GotClassMessage: <b>You are <i><color=red>SCP-966</color></i></b>! You are invisible until you interact with stuff.
  AbilityCoolownMessage: You are now visible!
  spawn_as: Scp0492
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A
