### ISSUE TITLE
roles_that_cant_damage doesn't work.

### ISSUE THREAD

**Issue by Bonjemus** [steven4547466/AdvancedSubclassing#33]
**Describe the bug**
"roles_that_cant_damage:" doesn't work (at least with SCPs).

**To Reproduce**
1. Set "roles_that_cant_damage:" to - Scp173.
2. Try to get killed by SCP-173.

**Expected behavior**
Normally you wouldn't be able to kill this subclass as SCP-173 but you are.

**Screenshots**

![Capture d’écran (142)](https://user-images.githubusercontent.com/59416055/99654519-bc545a00-2a5a-11eb-8745-5bff54279f8f.png)

**Config File**
Your config file.
```
name: UTR

affects_roles:
- FacilityGuard

string_options:
  Nickname: U.T.R. {name}
  GotClassMessage: Vous êtes un <color=grey>U.T.R</color>.
  AbilityCooldownMessage: ''
  Badge: U.T.R.
  BadgeColor: grey

boolean_options:
  Enabled: true
  DisregardHasFF: true
  HasFriendlyFire: true
  DisregardTakesFF: true
  TakesFriendlyFire: true
  AffectsSpawnWave: true

integer_options:
  MaxHealth: 220
  HealthOnSpawn: 220
  MaxArmor: 150
  ArmorOnSpawn: 150
  MaxAlive: 1

float_options:
  ChanceToGet: 25
  OnHitAmnesiaChance: 100
  OnHitAmnesiaDuration: 1
  OnHitDisabledChance: 100
  OnHitDisabledDuration: 10
  OnSpawnDisabledChance: 100
  OnSpawnDisabledDuration: 6000
  OnSpawnVisuals939Chance: 100
  OnSpawnVisuals939Duration: 6000
  OnSpawnVisueal939Intensity: 4
  ScaleY: 1.05
  ScaleX: 1.05
  ScaleZ: 1.05

spawn_locations:
- LczPlants

spawn_items:
  0:
    24: 100
  1:
    19: 100
  2:
    19: 100
  3:
    19: 100
  4:
    15: 100
  5:
    27: 100
  6:
    12: 100

spawn_ammo:
  Nato556: -1
  Nato762: -1
  Nato9: -1

abilities:
- InfiniteAmmo
- FlashImmune
- CantHeal
- Disable096Trigger
- Disable173Stop
- InfiniteSprint
- BypassKeycardReaders
- BypassTeslaGates
- CantBeSacraficed
- NoArmorDecay

ability_cooldowns:
  BypassKeycardReaders: 0
  BypassTeslaGates: 0
  Echolocate: 10

advanced_ff_rules:
- SCP-507

roles_that_cant_damage:
- Scp106
- Scp049
- Scp173

cant_damage:
- Scp049

ends_round_with: RIP

on_hit_effects:
- Amnesia
- Disabled

on_spawn_effects:
- Disabled
- Visuals939

spawns_as: NtfLieutenant
```

**Versioning**
 - AdvancedSubclassing Version : 1.2.2
 - Exiled Version : 2.1.15

**Additional context**
I was working before version 1.2.2 as long as I remember.
I tried it with SCP-049-2 and it doesn't work as well.

     - Sincerely Bonjemus.
