### ISSUE TITLE
Roundlock problem, again.

### ISSUE THREAD

**Issue by DatPanDat** [steven4547466/AdvancedSubclassing#37]
**Describe the bug**
Instead of enabling roundlock every time an spawn wave occur, roundlock will instead be disabled. Making 1 user testing impossible.

**To Reproduce**
1. Enable roundlock during the "waiting for players" phase or after the round has started.
2. Just start the game or wait for NTF / CI to spawn.

**Expected behavior**
Roundlock to be enabled.

**Screenshots**
N/A

**Config File** (Don't think it'll help, but I'm putting the [serverport]-config one here anyways.)
```yml
Subclass:
  is_enabled: true
  # Enable debug logs?
  debug: true
  # Makes chance to get classes additive instead of individual.
  additive_chance: true
  # The separator for spawn parameter arguments. Set this to (a) character(s) that are unique in class names, team names, etc.
  spawn_parameter_separator: _
  # The default time the got class broadcast lasts, still can be overridden by specific classes.
  global_broadcast_time: 12
  # The message shown to players when they try to go invisible, but already are.
  already_invisible_message: คุณล่องหนอยู่แล้ว!
  # The message shown to players when they fail to disguise.
  disguise_failed_message: การปลอมตัวล้มเหลว คนที่อยู่ใกล้คุณที่สุดคือทีมเดียวกับคุณ ไม่ก็เป็น SCP
  # The message shown to players when their revive fails because they aren't near a dead body.
  revive_failed_no_body_message: คุณต้องอยู่ใกล้ ๆ ศพ
  # The message shown to players when their revive fails because the body is not revivable.
  cant_revive_message: คุณไม่สามารถชุบชีวิตคนนี้ได้
  # The message shown to players when they use the help command and the class provided is not found.
  help_no_class_found: ไม่พบบทบาทนี้!
  # The message shown to players when they use the help command and the class provided has no help string.
  help_no_help_found: บทบาทนี้ไม่มีข้อมูลเพิ่มเติม
  # The message shown to players when they use the help command and provided no arguments.
  help_no_arguments_provided: กรุณาใส่ชื่อบทบาท หากคุณไม่ได้มีบทบาทพิเศษอยู่
  # The message shown to players when they use the an ability that requires spectators and there are none.
  no_available_spectators: ไม่มีคนที่ตายอยู่ ณ ตอนนี้
```

**Console Logs**
![image](https://user-images.githubusercontent.com/49842082/99911898-f909a500-2d29-11eb-8b36-8d53a2efdaae.png)

**Versioning**
 - AdvancedSubclassing Version (e.g. 1.0.0-pre013): 1.2.3
 - Exiled Version (e.g. 2.1.3): 2.1.18
