### ISSUE TITLE
Size don't always work

### ISSUE THREAD

**Issue by coco9515** [steven4547466/AdvancedSubclassing#40]
**Describe the bug**
The personalized size don't always work, it seems to be more particulary happening from the natural spawn - if I force a class, it gets its proper size.

**To Reproduce**
1. Create a class D with a special size; like 0.5
2. Naturaly spawn as this small class D - but don't be small.
3. Applied the "gsc" command to get the class, you will be small.

**Expected behavior**
Always size properly.

**Screenshots**
This one should be like 0.49
![20201225021316_1](https://user-images.githubusercontent.com/42412909/103132876-59805f00-46a7-11eb-8903-338d179b73b3.jpg)

**Config File**
Not the one from the screenshot, as this one is 1.1 size, but same problem.
```yml
# Name of the Class
name: Classe D Sprinteur

# Which roles can have this class
affects_roles:
- ClassD

string_options:
  # The message the user sees when they get the class.
  GotClassMessage: Tu es une classe sportive, tu peux courir des km sans t'essouffler !
  # The message players see when they attempt to use an ability that's on cooldown.
  AbilityCooldownMessage: Ta capacité {ability} est en rechargement pour {seconds} secondes !
  # A badge for the player.
  Badge: 
  # The color of the badge.
  BadgeColor: 
  # A message that will be announced by CASSIE when this subclass spawns.
  CassieMessage: 
  # The message people see when they run out of ability uses for any ability.
  OutOfAbilityUses: Tu n'as plus la capacité d'utiliser {ability} !
  # The message shown in player's consoles when they use the help command for this subclass.
  HelpMessage: Tu fais confiance à la fondation et tu ne dois pas te retourner contre eux à moins d'être maltraité ou de voir des actes horribles.

boolean_options:
  # Enables the class.
  Enabled: true
  # Disregards the value beneath it and uses the server default for friendly fire.
  DisregardHasFF: true
  # Enables friendly fire for this subclass, useful for traitorous subclasses, when a player with this option shoots a person on their team, everyone may shoot them regardless of DisregardTakesFF and TakesFriendlyFire.
  HasFriendlyFire: true
  # Disregards the value beneath it and uses the server default for friendly fire.
  DisregardTakesFF: true
  # Whether players on the same team of this subclass may shoot the player and may not be shot back.
  TakesFriendlyFire: true
  # If set to true, the subclass can only be given to a spawn wave. Defaults to false.
  OnlyAffectsSpawnWave: false
  # If set to true, the subclass can be given to both individuals and spawn waves. Defaults to false.
  AffectsSpawnWave: false
  # If set to false, the subclass will not be given to players after escaping. Defaults to true.
  GivenOnEscape: false

integer_options:
  # Max health of the class.
  MaxHealth: 100
  # The health the class spawns with.
  HealthOnSpawn: 100
  # Armor is a value that decreases over the course of the game, unless given the ability that stops it from doing so.
  # The max amount of armor the class has.
  MaxArmor: -1
  # The armor the class has on spawn.
  ArmorOnSpawn: -1
  # The max number of people that can have this class at any given moment - disregarding spawn waves.
  MaxAlive: 2
  # The max number of times this class can spawn per round. If this class is affecting a spawn wave, it is counted as 1. Defaults to an no max.
  MaxSpawnPerRound: 2
  # Any integer values from abilities go here as the <Ability>MaxUses

float_options:
  # The chance to get this class, not calculated with other classes for the same role.
  ChanceToGet: 7
  # The player's model scale across the selected axis.
  ScaleX: 1
  ScaleY: 1.2
  ScaleZ: 1
  # The player's spawn offset relative to the selected axis.
  SpawnOffsetX: 0
  SpawnOffsetY: 0
  SpawnOffsetZ: 0
  # The damage multiplier this player has. A value of 2 will double their damage.
  OnHitDamageMultiplier: 1
  # Any float values from abilities go here
  
# You may have a list of RoomTypes where this class is teleported to at the start of the round. Use Unknown for the default spawn location.
spawn_locations:
- Unknown

# "None" instead of any object means nothing would be added, but it still clears the player's inventory.
# It may be empty, if that's the case the value is "spawn_items: {}" then it would spawn with the default items from the role.
spawn_items:
  0:
    Coin: 40
  1:
    Painkillers: 10

# You can edit the default values of how must ammo a player has. Use -1 for default.
spawn_ammo:
  Nato556: -1
  Nato762: -1
  Nato9: -1

# Not all abilities are good, but they all add new things to the game.
# It may be empty, if that's the case, the value should be "abilities: []".
abilities:
- InfiniteSprint

# You can set custom cooldowns for abilities that have cooldowns.
# This list should contain all abilites that could have cooldowns that the class has, even if you set them to 0.
# It may be empty, if that's the case, the value should be "ability_cooldowns: {}".
ability_cooldowns: {}

# With this list, you can give a subclass a list of other subclasses they can friendly fire upon.
# This value is a list of strings (which are other subclass names). It may be empty, if that's the case, the value should be "advanced_ff_rules: []".
advanced_ff_rules: []

# This is a list of roles that are unable to damage the subclass regardless of team.
# If you want it to be empty, you can use "roles_that_cant_damage: []".
roles_that_cant_damage: []

# This is the Team that players with this class can end the game with. "RIP" means the default team.
ends_round_with: RIP

# This adds the ability to give players with certain subclasses the ability to inflict any effects upon damage a player.
# If there is anything in the list, you have to add those to the float_options : "OnHit<EFFECT_NAME>Chance" which is the chance for the effect to be applied.
# And there's "OnHit<EFFECT_NAME>Duration" this is optional and is the duration of the effect.
on_hit_effects: []

# This adds the ability to give players with certain subclasses any effects on spawn.
# If there is anything in the list, you have to add those to the float_options : "OnSpawn<EFFECT_NAME>Chance" which is the chance for the effect to be applied.
# And there's "OnSpawn<EFFECT_NAME>Duration" this is optional and is the duration of the effect.
on_spawn_effects: []

# This adds the ability to give players with certain subclasses any effects when they are damaged based on the damage type.
# If there is anything in the list, you have to add those to the float_options : "OnDamaged<EFFECT_NAME>Chance" which is the chance for the effect to be applied.
# And there's "OnDamaged<EFFECT_NAME>Duration" this is optional and is the duration of the effect.
#on_damaged_effects:

# It defines what role the class will spawn as. "None" is the default meaning they spawn as the role they were going to.
spawns_as: None

# These define what role the class becomes upon escaping. There are options for cuffed and not cuffed.
# If this is set to "None", or is not provided, it will use the default. This does not work on classes that cannot escape.
escapes_as:
  cuffed: NtfCadet
  not_cuffed: ChaosInsurgency
```

**Console Logs**
N/A

**Versioning**
 - AdvancedSubclassing Version 1.2.8
 - Exiled Version 2.1.21

**Additional context**
N/A
