### ISSUE TITLE
affects_roles: - ChaosInsurgency doesn't work

### ISSUE THREAD

**Issue by Oyplap** [steven4547466/AdvancedSubclassing#42]
**Describe the bug**
I tried to give ChaosInsurgency a custom class but it doesn't give anything.

**To Reproduce**
1. add in config: 

affects_roles:
- ChaosInsurgency

**Expected behavior**
That it works. That chaos gets a disarmer for example or a broadcast that is saying that you are a custom class.

**Config File**

[TestClass.txt](https://github.com/steven4547466/AdvancedSubclassing/files/5787904/TestClass.txt)

Changed it into txt instead of yml because i cant upload yml files here.

**Versioning**
 - AdvancedSubclassing Version (e.g. 1.0.0-pre013): 1.2.12
 - Exiled Version (e.g. 2.1.3): 2.1.27

**Comment by steven4547466** [comment]
Remove the spawn parameter. That spawn parameter is an example.

Try this:

```yml
name: TestClass

affects_roles:
- ChaosInsurgency

affects_users: {}

any_permissions: {}

string_options:
  GotClassMessage: You are an <color=red>ExampleClass</color>, this is an example test.
  AbilityCooldownMessage: Your {ability} ability is on cooldown for {seconds} seconds!
  OutOfAbilityUses: Your {ability} is out of uses!
  HelpMessage: Example help message.
  Nickname: Test {name}

boolean_options:
  Enabled: true
  DisregardHasFF: false
  HasFriendlyFire: false
  DisregardTakesFF: false
  TakesFriendlyFire: false
  GivenOnEscape: false

integer_options:
  MaxHealth: 150
  HealthOnSpawn: 150
  MaxArmor: -1
  ArmorOnSpawn: -1

float_options:
  ChanceToGet: 100
  VentDuration: 25
  PowerSurgeRadius: 30

spawn_locations:
- Unknown

spawn_items:
  0:
    GunCOM15: 100
  1:
    Disarmer: 100

spawn_ammo:
  Nato556: -1
  Nato762: -1
  Nato9: -1

abilities:
- Vent
- PowerSurge

ability_cooldowns: 
  Vent: 10
  PowerSurge: 10

initial_ability_cooldowns: {}

advanced_ff_rules: []

on_hit_effects: []

roles_that_cant_damage:
- Scp049

cant_damage:
- ClassD

on_spawn_effects: []
```
